services:
  pgvector:
    container_name: postgres
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_DB: myDB
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      VECTOR_STORE_TYPE: pgVector
      DIMENSIONS: 1024
    ports:
      - "5432:5432"